networks:
  forgejo:
    external: false

volumes:
  forgejo:
  mysql:  

services:
  server:
    image: codeberg.org/forgejo/forgejo:9
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=mysql
      - FORGEJO__database__HOST=db:3306
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=CHANGEME
    restart: unless-stopped
    networks:
      - forgejo
    volumes:
      - forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4773:3000"
      # - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=forgejo
      - MYSQL_USER=forgejo
      - MYSQL_PASSWORD=CHANGEME
      - MYSQL_DATABASE=forgejo
    networks:
      - forgejo
    volumes:
      - mysql:/var/lib/mysql

  # runner1:
  #   image: gitea/act_runner:latest
  #   restart: unless-stopped
  #   environment:
  #     - GITEA_INSTANCE_URL=https://code.termina.one
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=COOL_TOKEN
  #     - GITEA_RUNNER_NAME=forgejo-docker-1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
