version: "3.9"

services:
  fossbilling:
    build:
      context: .
      dockerfile_inline: |
        FROM fossbilling/fossbilling:latest
        RUN apt update && \
            apt install cron neovim -y && \
            apt clean && \
            rm -rf /var/lib/apt/lists/*
        RUN echo "*/5 * * * * root php /var/www/html/cron.php" >> /etc/crontab
        CMD ["sh", "-c", "cron ; apache2-foreground"]
    pull_policy: build
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - fossbilling:/var/www/html

  mysql:
    image: mysql:8.2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: CHANGE_ME
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  fossbilling:
  mysql:
