version: "3"

services:
  server:
    image: gitea/gitea:1.22.4
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=CHANGEME
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27122:3000"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - db-data:/var/lib/postgresql/data

  # runner1:
  #   image: gitea/act_runner:latest
  #   restart: unless-stopped
  #   environment:
  #     - GITEA_INSTANCE_URL=https://git.area96.digital
  #     - GITEA_RUNNER_REGISTRATION_TOKEN=COOL_TOKEN
  #     - GITEA_RUNNER_NAME=gitea-docker-1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db-data:
  gitea-data:

networks:
  gitea:
    external: false
