version: "3"

volumes:
  mysql_data:
  romm_resources:
  romm_redis_data:
  romm_library:
  romm_assets:
  romm_config:

services:
  romm:
    image: rommapp/romm:3.7.0
    restart: unless-stopped
    environment:
      - DB_HOST=romm-db
      - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
      - DB_USER=romm-user # Should match MARIADB_USER in mariadb
      - DB_PASSWD=CHANGEME # Should match MARIADB_PASSWORD in mariadb
      - ROMM_AUTH_SECRET_KEY=CHANGEME # Generate a key with `openssl rand -hex 32`
      - IGDB_CLIENT_ID=re4oit20ej19mhdaanu7f08me0tnoh # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET=6y7qgdpmexbh75j4u13gz0bivfjegu # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY= # https://www.mobygames.com/info/api/
      - STEAMGRIDDB_API_KEY=1c8413d567b4ab224e7005e001fc0ab0 # https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb
    volumes:
      - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - romm_redis_data:/redis-data # Cached data for background tasks
      - romm_library:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
      - romm_assets:/romm/assets # Uploaded saves, states, etc.
      - romm_config:/romm/config # Path where config.yml is stored
    ports:
      - 32210:8080
    depends_on:
      romm-db:
        condition: service_healthy
        restart: true

  romm-db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=CHANGEME # Use a unique, secure password
      - MARIADB_DATABASE=romm
      - MARIADB_USER=romm-user
      - MARIADB_PASSWORD=CHANGEME
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
