version: "3.8"
services:
  arma3:
    image: ghcr.io/gameservermanagers/gameserver:arma3
    restart: unless-stopped
    ports:
      - "2302:2302/udp"
      - "2303:2303/udp"
      - "2304:2304/udp"
      - "2305:2305/udp"
      - "2306:2306/udp"
    volumes:
      - data:/data

volumes:
  data:
